[package]
name    = "cellweave-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cellweave-core.workspace = true
thiserror.workspace      = true
ndarray.workspace        = true
rand.workspace           = true
rayon.workspace          = true
tracing.workspace        = true
